
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pip install -r ci/requirements_ci.txt
  displayName: 'Install requirements'

- script: |
    python ci/preprocess.py
    python ci/train.py
    python ci/model_eval.py
    python ci/register_model.py
  displayName: 'Run CI pipeline'
